
steps:
  - commands:
      - yarn install --immutable
      - yarn node -r '@swc/register' ./.buildkite/pipeline.ts
    plugins:
      - docker#v3.11.0:
          image: node:16-alpine
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"