
steps:
  - commands:
      - set -eux
      - yarn install --immutable
      - chown root /var/run/docker.sock
      - buildkite-pipelines ./.buildkite/pipeline.js | buildkite-agent pipeline upload
    plugins:
      - docker#v3.11.0:
          image: jameslnewell/buildkite-pipelines
          volumes:
            - /var/run/docker.sock:/var/run/docker.sock
          environment:
            - "BUILDKITE_BUILD_PATH=/var/lib/buildkite/builds"
          propagate-environment: true
      # - gencer/cache#v2.4.10:
      #     backend: rsync
      #     id: node
      #     key: "v2-cache-{{ id }}-{{ runner.os }}-{{ checksum 'yarn.lock' }}"
      #     restore-keys:
      #       - 'v2-cache-{{ id }}-{{ runner.os }}-'
      #       - 'v2-cache-{{ id }}-'
      #     paths:
      #       - .yarn/cache
      #     continue_on_error: true