
name: Pipeline

on:
  push:
    branches:
      - main

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          yarn install
          yarn run check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          yarn install
          yarn run test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          yarn install
          yarn run build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  docker-push:
    runs-on: ubuntu-latest
    needs: 
      - build
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: dist
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: jameslnewell/buildkite-pipelines:latest
  
  npm-publish:
    runs-on: ubuntu-latest
    needs: 
      - build
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: dist
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
